//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace ViewModels.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Order'.</summary>
	[Serializable]
	[DataContract]
	public partial class OrderViewModel
	{
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Order.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Note field. Derived from Entity Model Field 'Order.Note'</summary>
		[DataMember]
		public System.String Note { get; set; }
		/// <summary>Gets or sets the OrderPizzas field. </summary>
		[DataMember]
		public List<OrderViewModelTypes.OrderPizza> OrderPizzas { get; set; }
	}

	namespace OrderViewModelTypes
	{
		/// <summary> DTO class which is derived from the entity 'OrderPizza (OrderPizzas)'.</summary>
		[Serializable]
		[DataContract]
		public partial class OrderPizza
		{
			/// <summary>Gets or sets the Pizza field. </summary>
			[DataMember]
			public OrderPizzaTypes.Pizza Pizza { get; set; }
			/// <summary>Gets or sets the PizzaId field. Derived from Entity Model Field 'OrderPizza.PizzaId (FK)'</summary>
			[DataMember]
			public System.Int32 PizzaId { get; set; }
			/// <summary>Gets or sets the PizzaWithToppings field. </summary>
			[DataMember]
			public List<OrderPizzaTypes.PizzaWithTopping> PizzaWithToppings { get; set; }
		}

		namespace OrderPizzaTypes
		{
			/// <summary> DTO class which is derived from the entity 'Pizza (OrderPizzas.Pizza)'.</summary>
			[Serializable]
			[DataContract]
			public partial class Pizza
			{
				/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Pizza.Name'</summary>
				[DataMember]
				public System.String Name { get; set; }
				/// <summary>Gets or sets the Price field. Derived from Entity Model Field 'Pizza.Price'</summary>
				[DataMember]
				public System.Decimal Price { get; set; }
			}

			/// <summary> DTO class which is derived from the entity 'PizzaWithTopping (OrderPizzas.PizzaWithToppings)'.</summary>
			[Serializable]
			[DataContract]
			public partial class PizzaWithTopping
			{
				/// <summary>Gets or sets the Topping field. </summary>
				[DataMember]
				public PizzaWithToppingTypes.Topping Topping { get; set; }
				/// <summary>Gets or sets the ToppingId field. Derived from Entity Model Field 'PizzaWithTopping.ToppingId (FK)'</summary>
				[DataMember]
				public System.Int32 ToppingId { get; set; }
			}

			namespace PizzaWithToppingTypes
			{
				/// <summary> DTO class which is derived from the entity 'Topping (OrderPizzas.PizzaWithToppings.Topping)'.</summary>
				[Serializable]
				[DataContract]
				public partial class Topping
				{
					/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Topping.Name'</summary>
					[DataMember]
					public System.String Name { get; set; }
					/// <summary>Gets or sets the Price field. Derived from Entity Model Field 'Topping.Price'</summary>
					[DataMember]
					public System.Decimal Price { get; set; }
				}
			}
		}
	}

}




