//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ViewModels.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of ViewModels.DtoClasses.OrderViewModel from the entity model.</summary>
	public static partial class OrderViewModelPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.OrderEntity, ViewModels.DtoClasses.OrderViewModel>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<PizzaStore.Data.EntityClasses.OrderEntity, ViewModels.DtoClasses.OrderViewModel> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static OrderViewModelPersistence() { }
	
		/// <summary>Extension method which produces a projection to ViewModels.DtoClasses.OrderViewModel which instances are projected from the 
		/// results of the specified baseQuery, which returns PizzaStore.Data.EntityClasses.OrderEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve ViewModels.DtoClasses.OrderViewModel instances</returns>
		public static IQueryable<ViewModels.DtoClasses.OrderViewModel> ProjectToOrderViewModel(this IQueryable<PizzaStore.Data.EntityClasses.OrderEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to ViewModels.DtoClasses.OrderViewModel which instances are projected from the
		/// PizzaStore.Data.EntityClasses.OrderEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>PizzaStore.Data.EntityClasses.OrderEntity instance created from the specified entity instance</returns>
		public static ViewModels.DtoClasses.OrderViewModel ProjectToOrderViewModel(this PizzaStore.Data.EntityClasses.OrderEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.OrderEntity, ViewModels.DtoClasses.OrderViewModel>> CreateProjectionFunc()
		{
			return p__0 => new ViewModels.DtoClasses.OrderViewModel()
			{
				Id = p__0.Id,
				Note = p__0.Note,
				OrderPizzas = p__0.OrderPizzas.Select(p__1 => new ViewModels.DtoClasses.OrderViewModelTypes.OrderPizza()
				{
					Pizza = new ViewModels.DtoClasses.OrderViewModelTypes.OrderPizzaTypes.Pizza()
					{
						Name = p__1.Pizza.Name,
						Price = p__1.Pizza.Price,
					},
					PizzaId = p__1.PizzaId,
					PizzaWithToppings = p__1.PizzaWithToppings.Select(p__2 => new ViewModels.DtoClasses.OrderViewModelTypes.OrderPizzaTypes.PizzaWithTopping()
					{
						Topping = new ViewModels.DtoClasses.OrderViewModelTypes.OrderPizzaTypes.PizzaWithToppingTypes.Topping()
						{
							Name = p__2.Topping.Name,
							Price = p__2.Topping.Price,
						},
						ToppingId = p__2.ToppingId,
					}).ToList(),
				}).ToList(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_OrderViewModel 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

