//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PizzaStore.Read.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of PizzaStore.Read.DtoClasses.OrderView from the entity model.</summary>
	public static partial class OrderViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.OrderEntity, PizzaStore.Read.DtoClasses.OrderView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<PizzaStore.Data.EntityClasses.OrderEntity, PizzaStore.Read.DtoClasses.OrderView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static OrderViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to PizzaStore.Read.DtoClasses.OrderView which instances are projected from the 
		/// results of the specified baseQuery, which returns PizzaStore.Data.EntityClasses.OrderEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve PizzaStore.Read.DtoClasses.OrderView instances</returns>
		public static IQueryable<PizzaStore.Read.DtoClasses.OrderView> ProjectToOrderView(this IQueryable<PizzaStore.Data.EntityClasses.OrderEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to PizzaStore.Read.DtoClasses.OrderView which instances are projected from the
		/// PizzaStore.Data.EntityClasses.OrderEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>PizzaStore.Data.EntityClasses.OrderEntity instance created from the specified entity instance</returns>
		public static PizzaStore.Read.DtoClasses.OrderView ProjectToOrderView(this PizzaStore.Data.EntityClasses.OrderEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.OrderEntity, PizzaStore.Read.DtoClasses.OrderView>> CreateProjectionFunc()
		{
			return p__0 => new PizzaStore.Read.DtoClasses.OrderView()
			{
				Id = p__0.Id,
				Note = p__0.Note,
				OrderPizzas = p__0.OrderPizzas.Select(p__1 => new PizzaStore.Read.DtoClasses.OrderViewTypes.OrderPizza()
				{
					Id = p__1.Id,
					OrderId = p__1.OrderId,
					PizzaId = p__1.PizzaId,
					PizzaToppings = p__1.PizzaToppings.Select(p__2 => new PizzaStore.Read.DtoClasses.OrderViewTypes.OrderPizzaTypes.PizzaTopping()
					{
						Id = p__2.Id,
						OrderPizzaId = p__2.OrderPizzaId,
						ToppingId = p__2.ToppingId,
					}).ToList(),
				}).ToList(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_OrderView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

