//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PizzaStore.Read.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of PizzaStore.Read.DtoClasses.PizzaView from the entity model.</summary>
	public static partial class PizzaViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static PizzaViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to PizzaStore.Read.DtoClasses.PizzaView which instances are projected from the 
		/// results of the specified baseQuery, which returns PizzaStore.Data.EntityClasses.PizzaEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve PizzaStore.Read.DtoClasses.PizzaView instances</returns>
		public static IQueryable<PizzaStore.Read.DtoClasses.PizzaView> ProjectToPizzaView(this IQueryable<PizzaStore.Data.EntityClasses.PizzaEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to PizzaStore.Read.DtoClasses.PizzaView which instances are projected from the
		/// PizzaStore.Data.EntityClasses.PizzaEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>PizzaStore.Data.EntityClasses.PizzaEntity instance created from the specified entity instance</returns>
		public static PizzaStore.Read.DtoClasses.PizzaView ProjectToPizzaView(this PizzaStore.Data.EntityClasses.PizzaEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView>> CreateProjectionFunc()
		{
			return p__0 => new PizzaStore.Read.DtoClasses.PizzaView()
			{
				Id = p__0.Id,
				Ingredients = p__0.Ingredients,
				Name = p__0.Name,
				Price = p__0.Price,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_PizzaView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

