//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using SD.LLBLGen.Pro.QuerySpec;
using PizzaStore.Data.HelperClasses;
using SD.LLBLGen.Pro.LinqSupportClasses;

namespace PizzaStore.Read.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of PizzaStore.Read.DtoClasses.PizzaView from the entity model.</summary>
	public static partial class PizzaViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView> _compiledProjector = CreateProjectionFunc().Compile();
		/// <summary>Linq specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToPizzaView(System.Linq.IQueryable{PizzaStore.Data.EntityClasses.PizzaEntity})"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="CreateProjectionFunc"/></param>
		/// <remarks>Linq specific</remarks>
		static partial void GetAdjustmentsForProjectToPizzaView(ref System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView>> projectionAdjustments);
		/// <summary>QuerySpec specific partial method for obtaining projection adjustments for the projection method <see cref="ProjectToPizzaView(EntityQuery{PizzaStore.Data.EntityClasses.PizzaEntity}, PizzaStore.Data.FactoryClasses.QueryFactory)"/></summary>
		/// <param name="projectionAdjustments">Set this argument in an implementation of this partial method to a projection lambda similar to the generated projection in <see cref="ProjectToPizzaView(EntityQuery{PizzaStore.Data.EntityClasses.PizzaEntity}, PizzaStore.Data.FactoryClasses.QueryFactory)"/></param>
		/// <remarks>QuerySpec specific</remarks>
		static partial void GetAdjustmentsForProjectToPizzaViewQs(ref System.Linq.Expressions.Expression<Func<PizzaStore.Read.DtoClasses.PizzaView>> projectionAdjustments);
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static PizzaViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to PizzaStore.Read.DtoClasses.PizzaView which instances are projected from the 
		/// results of the specified baseQuery, which returns PizzaStore.Data.EntityClasses.PizzaEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve PizzaStore.Read.DtoClasses.PizzaView instances</returns>
		public static IQueryable<PizzaStore.Read.DtoClasses.PizzaView> ProjectToPizzaView(this IQueryable<PizzaStore.Data.EntityClasses.PizzaEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}

		/// <summary>Extension method which produces a projection to PizzaStore.Read.DtoClasses.PizzaView which instances are projected from the 
		/// results of the specified baseQuery using QuerySpec, which returns PizzaStore.Data.EntityClasses.PizzaEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <param name="qf">The query factory used to create baseQuery.</param>
		/// <returns>DynamicQuery to retrieve PizzaStore.Read.DtoClasses.PizzaView instances</returns>
		public static DynamicQuery<PizzaStore.Read.DtoClasses.PizzaView> ProjectToPizzaView(this EntityQuery<PizzaStore.Data.EntityClasses.PizzaEntity> baseQuery, PizzaStore.Data.FactoryClasses.QueryFactory qf)
		{
			System.Linq.Expressions.Expression<Func<PizzaStore.Read.DtoClasses.PizzaView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToPizzaViewQs(ref projectionAdjustments);
			return qf.Create()
				.From(baseQuery.Select(Projection.Full).As("__BQ"))
				.Select(LinqUtils.MergeProjectionAdjustmentsIntoProjection(() => new PizzaStore.Read.DtoClasses.PizzaView()
				{
					Id = PizzaFields.Id.Source("__BQ").ToValue<System.Int32>(),
					Ingredients = PizzaFields.Ingredients.Source("__BQ").ToValue<System.String>(),
					Name = PizzaFields.Name.Source("__BQ").ToValue<System.String>(),
					Price = PizzaFields.Price.Source("__BQ").ToValue<System.Decimal>(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegionQS_PizzaView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
				}, projectionAdjustments, false));
		}

		/// <summary>Extension method which produces a projection to PizzaStore.Read.DtoClasses.PizzaView which instances are projected from the
		/// PizzaStore.Data.EntityClasses.PizzaEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>PizzaStore.Data.EntityClasses.PizzaEntity instance created from the specified entity instance</returns>
		public static PizzaStore.Read.DtoClasses.PizzaView ProjectToPizzaView(this PizzaStore.Data.EntityClasses.PizzaEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView>> CreateProjectionFunc()
		{
			System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView>> mainProjection = p__0 => new PizzaStore.Read.DtoClasses.PizzaView()
			{
				Id = p__0.Id,
				Ingredients = p__0.Ingredients,
				Name = p__0.Name,
				Price = p__0.Price,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_PizzaView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
			System.Linq.Expressions.Expression<Func<PizzaStore.Data.EntityClasses.PizzaEntity, PizzaStore.Read.DtoClasses.PizzaView>> projectionAdjustments = null;
			GetAdjustmentsForProjectToPizzaView(ref projectionAdjustments);
			return LinqUtils.MergeProjectionAdjustmentsIntoProjection(mainProjection, projectionAdjustments, true);
		}
	}
}


