//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using PizzaStore.Data.FactoryClasses;
using PizzaStore.Data.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PizzaStore.Data.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitOrderEntityInfo();
			InitOrderPizzaEntityInfo();
			InitPizzaEntityInfo();
			InitPizzaToppingEntityInfo();
			InitToppingEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits OrderEntity's info objects</summary>
		private void InitOrderEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderFieldIndex), "OrderEntity");
			this.AddElementFieldInfo("OrderEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)OrderFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("OrderEntity", "Note", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.Note, 255, 0, 0);
		}

		/// <summary>Inits OrderPizzaEntity's info objects</summary>
		private void InitOrderPizzaEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderPizzaFieldIndex), "OrderPizzaEntity");
			this.AddElementFieldInfo("OrderPizzaEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)OrderPizzaFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("OrderPizzaEntity", "OrderId", typeof(System.Int32), false, true, false, false,  (int)OrderPizzaFieldIndex.OrderId, 0, 0, 10);
			this.AddElementFieldInfo("OrderPizzaEntity", "PizzaId", typeof(System.Int32), false, true, false, false,  (int)OrderPizzaFieldIndex.PizzaId, 0, 0, 10);
		}

		/// <summary>Inits PizzaEntity's info objects</summary>
		private void InitPizzaEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PizzaFieldIndex), "PizzaEntity");
			this.AddElementFieldInfo("PizzaEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)PizzaFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("PizzaEntity", "Ingredients", typeof(System.String), false, false, false, false,  (int)PizzaFieldIndex.Ingredients, 250, 0, 0);
			this.AddElementFieldInfo("PizzaEntity", "Name", typeof(System.String), false, false, false, false,  (int)PizzaFieldIndex.Name, 250, 0, 0);
			this.AddElementFieldInfo("PizzaEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)PizzaFieldIndex.Price, 0, 5, 19);
		}

		/// <summary>Inits PizzaToppingEntity's info objects</summary>
		private void InitPizzaToppingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PizzaToppingFieldIndex), "PizzaToppingEntity");
			this.AddElementFieldInfo("PizzaToppingEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)PizzaToppingFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("PizzaToppingEntity", "OrderPizzaId", typeof(System.Int32), false, true, false, false,  (int)PizzaToppingFieldIndex.OrderPizzaId, 0, 0, 10);
			this.AddElementFieldInfo("PizzaToppingEntity", "ToppingId", typeof(System.Int32), false, true, false, false,  (int)PizzaToppingFieldIndex.ToppingId, 0, 0, 10);
		}

		/// <summary>Inits ToppingEntity's info objects</summary>
		private void InitToppingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ToppingFieldIndex), "ToppingEntity");
			this.AddElementFieldInfo("ToppingEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)ToppingFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("ToppingEntity", "Name", typeof(System.String), false, false, false, false,  (int)ToppingFieldIndex.Name, 250, 0, 0);
			this.AddElementFieldInfo("ToppingEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)ToppingFieldIndex.Price, 0, 5, 19);
		}
	}
}