//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace PizzaStore.Read.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Order'.</summary>
	[Serializable]
	[DataContract]
	public partial class OrderView
	{
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Order.Id'</summary>
		[DataMember]
		public System.Int32 Id { get; set; }
		/// <summary>Gets or sets the Note field. Derived from Entity Model Field 'Order.Note'</summary>
		[DataMember]
		public System.String Note { get; set; }
		/// <summary>Gets or sets the OrderPizzas field. </summary>
		[DataMember]
		public List<OrderViewTypes.OrderPizza> OrderPizzas { get; set; }
	}

	namespace OrderViewTypes
	{
		/// <summary> DTO class which is derived from the entity 'OrderPizza (OrderPizzas)'.</summary>
		[Serializable]
		[DataContract]
		public partial class OrderPizza
		{
			/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'OrderPizza.Id'</summary>
			[DataMember]
			public System.Int32 Id { get; set; }
			/// <summary>Gets or sets the OrderId field. Derived from Entity Model Field 'OrderPizza.OrderId (FK)'</summary>
			[DataMember]
			public System.Int32 OrderId { get; set; }
			/// <summary>Gets or sets the PizzaId field. Derived from Entity Model Field 'OrderPizza.PizzaId (FK)'</summary>
			[DataMember]
			public System.Int32 PizzaId { get; set; }
			/// <summary>Gets or sets the PizzaToppings field. </summary>
			[DataMember]
			public List<OrderPizzaTypes.PizzaTopping> PizzaToppings { get; set; }
		}

		namespace OrderPizzaTypes
		{
			/// <summary> DTO class which is derived from the entity 'PizzaTopping (OrderPizzas.PizzaToppings)'.</summary>
			[Serializable]
			[DataContract]
			public partial class PizzaTopping
			{
				/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'PizzaTopping.Id'</summary>
				[DataMember]
				public System.Int32 Id { get; set; }
				/// <summary>Gets or sets the OrderPizzaId field. Derived from Entity Model Field 'PizzaTopping.OrderPizzaId (FK)'</summary>
				[DataMember]
				public System.Int32 OrderPizzaId { get; set; }
				/// <summary>Gets or sets the ToppingId field. Derived from Entity Model Field 'PizzaTopping.ToppingId (FK)'</summary>
				[DataMember]
				public System.Int32 ToppingId { get; set; }
			}
		}
	}

}




