//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.9.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace PizzaStore.Data
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Order</summary>
		OrderEntity,
		///<summary>OrderPizza</summary>
		OrderPizzaEntity,
		///<summary>Pizza</summary>
		PizzaEntity,
		///<summary>PizzaTopping</summary>
		PizzaToppingEntity,
		///<summary>Topping</summary>
		ToppingEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END

}

