//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using PizzaStore.Data.HelperClasses;
using PizzaStore.Data.FactoryClasses;
using PizzaStore.Data.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PizzaStore.Data.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Topping'.<br/><br/></summary>
	[Serializable]
	public partial class ToppingEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<PizzaToppingEntity> _pizzaToppings;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ToppingEntityStaticMetaData _staticMetaData = new ToppingEntityStaticMetaData();
		private static ToppingRelations _relationsFactory = new ToppingRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name PizzaToppings</summary>
			public static readonly string PizzaToppings = "PizzaToppings";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ToppingEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ToppingEntityStaticMetaData()
			{
				SetEntityCoreInfo("ToppingEntity", InheritanceHierarchyType.None, false, (int)PizzaStore.Data.EntityType.ToppingEntity, typeof(ToppingEntity), typeof(ToppingEntityFactory), false);
				AddNavigatorMetaData<ToppingEntity, EntityCollection<PizzaToppingEntity>>("PizzaToppings", a => a._pizzaToppings, (a, b) => a._pizzaToppings = b, a => a.PizzaToppings, () => new ToppingRelations().PizzaToppingEntityUsingToppingId, typeof(PizzaToppingEntity), (int)PizzaStore.Data.EntityType.PizzaToppingEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ToppingEntity()
		{
		}

		/// <summary> CTor</summary>
		public ToppingEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ToppingEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ToppingEntity</param>
		public ToppingEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Topping which data should be fetched into this Topping object</param>
		public ToppingEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Topping which data should be fetched into this Topping object</param>
		/// <param name="validator">The custom validator object for this ToppingEntity</param>
		public ToppingEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ToppingEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'PizzaTopping' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPizzaToppings() { return CreateRelationInfoForNavigator("PizzaToppings"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ToppingEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ToppingRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'PizzaTopping' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPizzaToppings { get { return _staticMetaData.GetPrefetchPathElement("PizzaToppings", CommonEntityBase.CreateEntityCollection<PizzaToppingEntity>()); } }

		/// <summary>The Id property of the Entity Topping<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Topping"."Id".<br/>Table field type characteristics (type, precision, scale, length): Int, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)ToppingFieldIndex.Id, true); }
			set { SetValue((int)ToppingFieldIndex.Id, value); }		}

		/// <summary>The Name property of the Entity Topping<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Topping"."Name".<br/>Table field type characteristics (type, precision, scale, length): NVarChar, 0, 0, 250.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ToppingFieldIndex.Name, true); }
			set	{ SetValue((int)ToppingFieldIndex.Name, value); }
		}

		/// <summary>The Price property of the Entity Topping<br/><br/></summary>
		/// <remarks>Mapped on  table field: "Topping"."Price".<br/>Table field type characteristics (type, precision, scale, length): Decimal, 19, 5, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Price
		{
			get { return (System.Decimal)GetValue((int)ToppingFieldIndex.Price, true); }
			set	{ SetValue((int)ToppingFieldIndex.Price, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'PizzaToppingEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PizzaToppingEntity))]
		public virtual EntityCollection<PizzaToppingEntity> PizzaToppings { get { return GetOrCreateEntityCollection<PizzaToppingEntity, PizzaToppingEntityFactory>("Topping", true, false, ref _pizzaToppings); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace PizzaStore.Data
{
	public enum ToppingFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Name. </summary>
		Name,
		///<summary>Price. </summary>
		Price,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace PizzaStore.Data.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Topping. </summary>
	public partial class ToppingRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ToppingEntity and PizzaToppingEntity over the 1:n relation they have, using the relation between the fields: Topping.Id - PizzaTopping.ToppingId</summary>
		public virtual IEntityRelation PizzaToppingEntityUsingToppingId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "PizzaToppings", true, new[] { ToppingFields.Id, PizzaToppingFields.ToppingId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticToppingRelations
	{
		internal static readonly IEntityRelation PizzaToppingEntityUsingToppingIdStatic = new ToppingRelations().PizzaToppingEntityUsingToppingId;

		/// <summary>CTor</summary>
		static StaticToppingRelations() { }
	}
}
